$BOX       = "rgl/windows-server-2019-standard-amd64"
$HOSTNAME  = "LAB1SRV1"
$adminpass = "P@ssw0rd"
$net1      = "VirtualBox Host-Only Ethernet Adapter #2"
$net2      = "VirtualBox Host-Only Ethernet Adapter #3"

required_plugins = %w( vagrant-reload vagrant-vbguest )
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin};vagrant #{ARGV.join(" ")}" unless Vagrant.has_plugin? plugin || ARGV[0] == 'plugin'
end

servers=[
  {
    :hostname => "LAB1ACC1",
    :net      => $net1,
    :ram      => 1024,
    :cpu      => 1
  },
  {
    :hostname => "LAB1BUS1",
    :net      => $net2,
    :ram      => 1024,
    :cpu      => 1
  }
]

Vagrant.configure(2) do |config|

    config.vm.box = "rgl/windows-server-2019-standard-amd64"
    config.vm.box_check_update = false

    config.vm.define $HOSTNAME do |master|

        master.vm.provider "virtualbox" do |vb, override|
          vb.name = $HOSTNAME
          vb.customize ["modifyvm", :id, "--memory", 2048]
          vb.customize ["modifyvm", :id, "--cpus", 2]
          vb.customize ["modifyvm", :id, "--vram", "32"]
          vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
        end


        master.vm.hostname = $HOSTNAME
        master.vm.guest = :windows
        master.vm.boot_timeout = 600
        master.vm.communicator = "winrm"
        master.winrm.transport = :plaintext
        master.winrm.basic_auth_only = true
        master.winrm.username = "vagrant"
        master.winrm.password = "vagrant"
        master.winrm.timeout = 300
        master.winrm.retry_limit = 20

        master.vm.network :private_network, ip: "192.168.1.2", netmask: "255.255.255.0", mac: "080027AAAAA1"
        master.vm.network :private_network, ip: "192.168.2.2", netmask: "255.255.255.0", mac: "080027AAAAA2"
        master.vm.provision "shell", path: "files/pre-install.ps1", privileged: true, args: $adminpass
        master.vm.provision "shell", path: "files/bootstrap.ps1", privileged: true
        # master.vm.provision :reload
    end

    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|

            node.vm.provider "virtualbox" do |vb, override|
                vb.name = machine[:hostname]
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyvm", :id, "--cpus", machine[:cpu]]
                vb.customize ["modifyvm", :id, "--vram", "32"]
                vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
                vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
                vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]

                vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
                vb.customize ["modifyvm", :id, "--hostonlyadapter2", machine[:net]]
                vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
            end

            node.vm.hostname = machine[:hostname]
            node.vm.guest = :windows
            node.vm.boot_timeout = 600
            node.vm.communicator = "winrm"
            node.winrm.transport = :plaintext
            node.winrm.basic_auth_only = true
            node.winrm.username = "vagrant"
            node.winrm.password = "vagrant"
            node.winrm.timeout = 300
            node.winrm.retry_limit = 20

            node.vm.provision "shell", path: "files/pre-install.ps1", privileged: true, args: $adminpass
            # node.vm.provision "shell", inline: <<-SHELL
                # powershell -windowstyle hidden -command netsh interface set interface "Ethernet" disable
            # SHELL
        end
    end
end